/*
EJBCA REST Interface

Testing V1SshApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ejbca

import (
	"context"
	openapiclient "github.com/Keyfactor/ejbca-go-client-sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_ejbca_V1SshApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test V1SshApiService Pubkey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var caName string

		resp, httpRes, err := apiClient.V1SshApi.Pubkey(context.Background(), caName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V1SshApiService Status8", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.V1SshApi.Status8(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
