/*
EJBCA REST Interface

Testing V1CaManagementApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ejbca

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Keyfactor/ejbca-go-client-sdk/ejbca"
)

func Test_ejbca_V1CaManagementApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test V1CaManagementApiService Activate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var caName string

		httpRes, err := apiClient.V1CaManagementApi.Activate(context.Background(), caName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V1CaManagementApiService Deactivate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var caName string

		httpRes, err := apiClient.V1CaManagementApi.Deactivate(context.Background(), caName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V1CaManagementApiService Status", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.V1CaManagementApi.Status(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
